mybatis-plus:
  type-aliases-package: com.chen.cache.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-not-delete-value: 0

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    master:
      url: jdbc:mysql://124.223.5.106:3307/school?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    slave01:
      url: jdbc:mysql://124.223.5.106:3308/school?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource

