mybatis-plus:
  type-aliases-package: com.chen.cache.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-not-delete-value: 0

spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    master:
      url: jdbc:mysql://localhost:3307/school?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    slave01:
      url: jdbc:mysql://localhost:3308/school?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: test
      auto-commit-interval: 1000
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        session.timeout.ms: 15000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

